language: cpp

matrix:
  include:
    os: linux
          addons:
            apt:
              sources:
                - ubuntu-toolchain-r-test
              packages:
                - g++-9
          env:
            - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"

branches:
  only:
    - main

before_install:
    - eval "${MATRIX_EVAL}"
install: ./install-dependencies.sh
script: make
